/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/campfire` | `/campfire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/legacy` | `/legacy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/standings` | `/standings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(match)'}/replay` | `/replay`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(match)'}/[fixtureId]` | `/[fixtureId]`, params: Router.UnknownInputParams & { fixtureId: string | number; } } | { pathname: `${'/(match)'}/replay/[fixtureId]` | `/replay/[fixtureId]`, params: Router.UnknownInputParams & { fixtureId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/campfire` | `/campfire`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/legacy` | `/legacy`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/standings` | `/standings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(match)'}/replay` | `/replay`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(match)'}/[fixtureId]` | `/[fixtureId]`, params: Router.UnknownOutputParams & { fixtureId: string; } } | { pathname: `${'/(match)'}/replay/[fixtureId]` | `/replay/[fixtureId]`, params: Router.UnknownOutputParams & { fixtureId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/campfire${`?${string}` | `#${string}` | ''}` | `/campfire${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/legacy${`?${string}` | `#${string}` | ''}` | `/legacy${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/standings${`?${string}` | `#${string}` | ''}` | `/standings${`?${string}` | `#${string}` | ''}` | `${'/(match)'}/replay${`?${string}` | `#${string}` | ''}` | `/replay${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/campfire` | `/campfire`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/legacy` | `/legacy`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/standings` | `/standings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(match)'}/replay` | `/replay`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `${'/(match)'}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(match)'}/replay/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/replay/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(match)'}/[fixtureId]` | `/[fixtureId]`, params: Router.UnknownInputParams & { fixtureId: string | number; } } | { pathname: `${'/(match)'}/replay/[fixtureId]` | `/replay/[fixtureId]`, params: Router.UnknownInputParams & { fixtureId: string | number; } };
    }
  }
}
